export const env = {
	BASE_URL: process.env.BASE_URL!,
	DEFAULT_REDIRECT_URL: process.env.DEFAULT_REDIRECT_URL!,
	EMAIL_VERIFICATION_CALLBACK_URL: process.env.EMAIL_VERIFICATION_CALLBACK_URL!,
	DATABASE_URL: process.env.DATABASE_URL!,
	RESEND_API_KEY: process.env.RESEND_API_KEY!,
};
